# syntax=docker/dockerfile:1

# Этап сборки
FROM python:3.9-slim as builder

# Установка рабочей директории
WORKDIR /app

# Установка необходимых зависимостей
RUN apt-get update && apt-get install -y \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

# Установка зависимостей Python
COPY requirements.txt .
RUN pip install --user -r requirements.txt

# Загрузка модели
RUN python -c "import whisper; whisper.load_model('large')"

# Финальный этап
FROM python:3.9-slim
WORKDIR /app

# Копирование зависимостей и модели из этапа сборки
COPY --from=builder /root/.local /root/.local
COPY --from=builder /usr/bin/ffmpeg /usr/bin/ffmpeg

# Убедитесь, что скрипты в .local доступны
ENV PATH=/root/.local/bin:$PATH

# Копирование кода приложения
COPY . .

# Проверка наличия ffmpeg (опционально)
RUN ffmpeg -version

# Запуск приложения
CMD ["python", "bot.py"]