services:
  bot:
    image: kinzul/audio-messages-bot:latest
    container_name: whisper_bot
    volumes:
      - whisper_models:/root/.cache/whisper
    restart: unless-stopped
    mem_limit: 900m
    command: >
      sh -c "python -c 'import whisper; whisper.load_model(\"base\")' &&
             python bot.py"

volumes:
  whisper_models: 